### ISSUE TITLE
Fix since and until build — otherwise it is impossible to install plugin

### ISSUE THREAD

**Issue by develar** [eddysystems/issues#1]
https://plugins.jetbrains.com/plugin/7688?pr=

Must be 139.\* and 140._, but not 40._

**Comment by martinwicke** [comment]
Thanks! Do you know where the 40 comes from? It says "139" and "140" in plugin.xml. I'll change that to "139.*", is that the right syntax?

**Comment by develar** [comment]
"139" is not correct, sorry, but due to historical reasons it is not parsed correctly.

plugin for 140:

```
<idea-version since-build="140.0" until-build="141.0"/>
```

plugin for 139:

```
<idea-version since-build="139.0" until-build="140.0"/>
```

Here until-build is used for 140 also, to ensure that plugin will not be compatible with next major IDEA version (it is useful if you publish plugin frequently).

**Comment by martinwicke** [comment]
I think github ate the xml (I assume there was something in the "for 139" and "for 140" lines). Could you write that again, maybe just the attribute values?

**Comment by martinwicke** [comment]
never mind. It's just the display.

**Comment by martinwicke** [comment]
Should be fixed in new upload.

**Comment by develar** [comment]
Thanks, but could you please publish plugin for IDEA 14.1 (141 branch)?

**Comment by martinwicke** [comment]
I'm happy to adjust the until-build of the 0.1-14 plugin to be 141.0, is that what you meant?

I couldn't find a 141 branch in the intellij-community repository (https://github.com/JetBrains/intellij-community/branches/all), does it exist yet?

Vladimir Krivosheev wrote:

**Comment by develar** [comment]
Sorry for misunderstanding, IDEA 14.1 is 140, of course.

https://plugins.jetbrains.com/plugin/7688?pr=idea

I see 0.1-14., but "Until Build" == 140. 

IDEA 14.0 — 139 branch.
upcoming IDEA 14.1 — 140 (branch master, because is not yet released). https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP

**Comment by martinwicke** [comment]
I changed until-build to 141.0 and updated.
